# Generated by Django 5.1.7 on 2025-03-31 16:32

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('group', models.CharField(max_length=20, verbose_name='Группа')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Номер студенческого')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_path, verbose_name='Фото')),
                ('characteristics', models.TextField(verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
