# Generated by Django 5.1.7 on 2025-04-07 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='characteristics/', verbose_name='Файл характеристики')),
                ('text', models.TextField(verbose_name='Текст характеристики')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Характеристика из Word',
                'verbose_name_plural': 'Характеристики из Word',
            },
        ),
    ]
