# Generated by Django 5.2 on 2025-04-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentcharacteristic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Talyp', 'verbose_name_plural': 'Talyplar'},
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год поступления'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_place',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
