# Generated by Django 5.2 on 2025-04-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_forma2_relative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='relationship',
            field=models.CharField(choices=[('father', 'Atasy'), ('mother', 'Enesi'), ('grandfather', 'Babasy'), ('grandmother', 'Mamasy'), ('sister', 'Kakasy'), ('brother', 'Ejesi'), ('female_sibling', 'Ayal dogany'), ('male_sibling', 'Erkek dogany')], max_length=20, verbose_name='Родство'),
        ),
    ]
