# Generated by Django 5.2 on 2025-04-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_relative_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.IntegerField(choices=[(1, '1-nji kurs'), (2, '2-nji kurs'), (3, '3-nji kurs'), (4, '4-nji kurs'), (4, '5-nji kurs')], default=3, verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('physics', 'Fizika'), ('mathematics', 'Matematika'), ('chemistry', 'Himiýa'), ('biology', 'Biologiýa')], default='physics', max_length=50, verbose_name='Fakultet'),
        ),
    ]
