# Generated by Django 4.2.16 on 2025-04-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_relative_options_remove_relative_phone_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course'], name='students_st_course_639de9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['faculty'], name='students_st_faculty_ca7b89_idx'),
        ),
    ]
